### ISSUE TITLE
Response "Oops! Response Exception", when chat with knowledgebase

### ISSUE THREAD

**Issue by wyxogo** [sugarforever/chat-ollama#409]
I can successfully chat on chatollama without knowledgebase, but selecting a created knowledgebase(only one PDF file), failed respond:
![image](https://github.com/sugarforever/chat-ollama/assets/61509470/d061c998-30e9-439e-9735-41743880c81a)
then: 
![image](https://github.com/sugarforever/chat-ollama/assets/61509470/3b71414e-0ebf-4033-acde-56357564528c)

**Comment by sugarforever** [comment]
May I query what chat model you used? As you were already in the chat, I suppose Chromadb was up and running. I will try to reproduce.

**Comment by wyxogo** [comment]
It may be a embedding problem. How do I use a locally downloaded embedding

**Comment by sugarforever** [comment]
You can go to Models to download an Ollama embedding model. When you create a knowledge base, instead of choosing an embedding model from the drop down list, manually type the Ollama embedding model you'd like to use.
<img width="676" alt="Screenshot 2024-05-01 at 10 55 58 AM" src="https://github.com/sugarforever/chat-ollama/assets/404421/532350bb-fc10-4301-9a68-6c1bf16f1d22">

**Comment by wyxogo** [comment]
I enter the embedding model name directly. Now it works normally. 
thx

**Comment by sugarforever** [comment]
> I enter the embedding model name directly. Now it works normally. thx

That's good news. :-)
